name: Build Python (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          set -eux
          sudo pacman -Sy --noconfirm \
            python \
            wine \
            winetricks \
            wget \
            curl \
            unzip \
            p7zip \
            wine \
            xorg-server-xvfb

          export WINEPREFIX=$HOME/.local/share/wineprefixes/nuitka
          mkdir -p "$WINEPREFIX"

      - name: Build project
        run: |
          chmod +x Cross_compile.sh
          xvfb-run ./Cross_compile.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: OutlastTogether
          path: |
            OutlastTogether.exe
