name: Build Python (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          set -eux
          sudo dpkg --add-architecture i386
          mkdir -pm755 /etc/apt/keyrings && \
          curl -fsSL https://dl.winehq.org/wine-builds/winehq.key \
            -o /etc/apt/keyrings/winehq-archive.key && \
          curl -fsSL https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources \
              -o /etc/apt/sources.list.d/winehq-noble.sources && \
          apt-get update && \
          apt-get install -y --install-recommends winehq-devel
          wine --version
          sudo apt-get update
          sudo apt-get install -y \
          python3 \
          winetricks \
          wget \
          libwbclient0 \
          unzip \
          7zip


      - name: Build project
        run: |
          chmod +x Cross_compile.sh
          ./Cross_compile.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: OutlastTogether
          path: |
            OutlastTogether.exe
