name: Build Python (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          set -eux
          pacman -Sy --noconfirm \
            python \
            wine \
            winetricks \
            wget \
            curl \
            unzip \
            p7zip \
            xorg-server-xvfb

      - name: Build project
        run: |
          chmod +x Cross_compile.sh
          ./Cross_compile.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: OutlastTogether
          path: |
            OutlastTogether.exe
